### ISSUE TITLE
Kood pakkimata kujul

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused_kood#1]
Koodi peaks repos olema pakkimata kujul ;)

**Comment by RRisto** [comment]
Tegelikult on seepakett mõeldud selleks, et esimene piloteerija Kultuuriministeerium saaks koodi kiirelt kätte ja proovida selle püsti panna. Tegelikult peaks kood hakkama elama Riigikantselei valitsusveebi branchis. Seega on see ajutine lahendus, mille pärast pilooti tahaks ära koristada. Koodihaldus ja jagamine peaks valitsusveebi reposse minema :)

**Comment by tormi** [comment]
Ok, guud ;)
